plugins {
    id 'application'
    id 'java'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

group = 'sg.edu.nus.cs3227'
version = '0.1.0'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

javafx {
    version = '21.0.6'
    modules = ['javafx.controls']
}

dependencies {
    implementation 'com.h2database:h2:2.5.250'
    testImplementation platform('org.junit:junit-bom:5.12.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

application {
    mainClass = 'loandesk.LoanDeskApp'
}

tasks.named('test') {
    useJUnitPlatform()
}
